export const mockCapsules = [
    {
        id: 'c1',
        ownerId: 'u1',
        title: 'Final Letter to Myself',
        message: 'Remember who you are and what you’ve done.',
        attachments: [
            { path: 'memory.jpg', size: 1.2, type: 'image/jpeg' },
            { path: 'letter.pdf', size: 0.3, type: 'application/pdf' },
        ],
        attachmentsSize: 1.5,
        delivered: true,
        deliveryDate: new Date('2024-03-15T10:00:00Z'),
        readCount: 8,
        createdAt: new Date('2024-01-10T15:30:00Z'),
    },
    {
        id: 'c2',
        ownerId: 'u2',
        title: 'Time Capsule to Friends',
        message: 'We made it to 2030! Cheers!',
        attachments: [
            { path: 'toast.mp4', size: 10.0, type: 'video/mp4' },
        ],
        attachmentsSize: 10.0,
        delivered: true,
        deliveryDate: new Date('2024-04-01T12:00:00Z'),
        readCount: 25,
        createdAt: new Date('2023-12-20T08:45:00Z'),
    },
    {
        id: 'c3',
        ownerId: 'u3',
        title: 'Milestone Achievements',
        message: 'All the goals we accomplished together',
        attachments: [
            { path: 'achievements.pdf', size: 2.1, type: 'application/pdf' },
            { path: 'celebration.mp4', size: 15.5, type: 'video/mp4' },
        ],
        attachmentsSize: 17.6,
        delivered: true,
        deliveryDate: new Date('2024-02-28T09:30:00Z'),
        readCount: 12,
        createdAt: new Date('2023-11-05T14:20:00Z'),
    },
    {
        id: 'c4',
        ownerId: 'u4',
        title: 'Future Predictions',
        message: 'How accurate were our guesses about the future?',
        attachments: [
            { path: 'predictions.txt', size: 0.1, type: 'text/plain' },
        ],
        attachmentsSize: 0.1,
        delivered: true,
        deliveryDate: new Date('2024-01-01T00:00:00Z'),
        readCount: 42,
        createdAt: new Date('2020-12-31T23:59:00Z'),
    },
    {
        id: 'c5',
        ownerId: 'u5',
        title: 'Family Memories 2025',
        message: 'Our year in review',
        attachments: [
            { path: 'family.jpg', size: 3.2, type: 'image/jpeg' },
            { path: 'vacation.mp4', size: 8.7, type: 'video/mp4' },
            { path: 'audio_note.mp3', size: 1.8, type: 'audio/mp3' },
        ],
        attachmentsSize: 13.7,
        delivered: true,
        deliveryDate: new Date('2024-03-20T18:00:00Z'),
        readCount: 5,
        createdAt: new Date('2024-01-05T10:15:00Z'),
    },
]